/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveySlugRouteImport } from './routes/survey.$slug'
import { Route as SurveysIdResponsesRouteImport } from './routes/surveys.$id.responses'
import { Route as SurveysIdEditRouteImport } from './routes/surveys.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveySlugRoute = SurveySlugRouteImport.update({
  id: '/survey/$slug',
  path: '/survey/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIdResponsesRoute = SurveysIdResponsesRouteImport.update({
  id: '/$id/responses',
  path: '/$id/responses',
  getParentRoute: () => SurveysRoute,
} as any)
const SurveysIdEditRoute = SurveysIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => SurveysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/terms': typeof TermsRoute
  '/survey/$slug': typeof SurveySlugRoute
  '/surveys/$id/edit': typeof SurveysIdEditRoute
  '/surveys/$id/responses': typeof SurveysIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/terms': typeof TermsRoute
  '/survey/$slug': typeof SurveySlugRoute
  '/surveys/$id/edit': typeof SurveysIdEditRoute
  '/surveys/$id/responses': typeof SurveysIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/terms': typeof TermsRoute
  '/survey/$slug': typeof SurveySlugRoute
  '/surveys/$id/edit': typeof SurveysIdEditRoute
  '/surveys/$id/responses': typeof SurveysIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/surveys'
    | '/terms'
    | '/survey/$slug'
    | '/surveys/$id/edit'
    | '/surveys/$id/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/surveys'
    | '/terms'
    | '/survey/$slug'
    | '/surveys/$id/edit'
    | '/surveys/$id/responses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/surveys'
    | '/terms'
    | '/survey/$slug'
    | '/surveys/$id/edit'
    | '/surveys/$id/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SurveysRoute: typeof SurveysRouteWithChildren
  TermsRoute: typeof TermsRoute
  SurveySlugRoute: typeof SurveySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$slug': {
      id: '/survey/$slug'
      path: '/survey/$slug'
      fullPath: '/survey/$slug'
      preLoaderRoute: typeof SurveySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$id/responses': {
      id: '/surveys/$id/responses'
      path: '/$id/responses'
      fullPath: '/surveys/$id/responses'
      preLoaderRoute: typeof SurveysIdResponsesRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/surveys/$id/edit': {
      id: '/surveys/$id/edit'
      path: '/$id/edit'
      fullPath: '/surveys/$id/edit'
      preLoaderRoute: typeof SurveysIdEditRouteImport
      parentRoute: typeof SurveysRoute
    }
  }
}

interface SurveysRouteChildren {
  SurveysIdEditRoute: typeof SurveysIdEditRoute
  SurveysIdResponsesRoute: typeof SurveysIdResponsesRoute
}

const SurveysRouteChildren: SurveysRouteChildren = {
  SurveysIdEditRoute: SurveysIdEditRoute,
  SurveysIdResponsesRoute: SurveysIdResponsesRoute,
}

const SurveysRouteWithChildren =
  SurveysRoute._addFileChildren(SurveysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SurveysRoute: SurveysRouteWithChildren,
  TermsRoute: TermsRoute,
  SurveySlugRoute: SurveySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
